name: CI
on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:
jobs:
  aur:
    name: Bump in your AUR packages
    runs-on: ubuntu-latest
    environment: AUR
    permissions:
      contents: write
    container: archlinux:multilib-devel
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: pacman -Syu --needed --noconfirm pacman-contrib namcap git devtools
      - name: Create build user and setup permissions
        run: |
          useradd -m -s /bin/bash builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder ${{ github.workspace }}
      - name: Install Bumper
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: bcyran/bumper
          cache: enable
      - run: bumper --version
      - run: su - builder -c "bumper packages/"
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          file_pattern: 'packages/*'
